import React, { useState } from 'react';
import { Linking, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LpaIcon as Feather } from '@/components/LpaIcon';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';
import { useApp } from '@/context/AppContext';

const forms = [
  { title: 'Absence/tardy form', copy: 'Let the team know when plans change.', icon: 'clock' as const, tint: '#AB562B', url: 'https://forms.cloud.microsoft/pages/responsepage.aspx?id=41OaSypLA0yoKGPBLTVM_zR74t7B3VJCujiML5HMn9RUOEkyT045MklRRzRHOExJOFhRTDRCQlZRSi4u&route=shorturl' },
  { title: 'LPA External Training & Competition Request Form', copy: 'Share outside training and competition details.', icon: 'award' as const, tint: '#9BC7BD', url: 'https://forms.cloud.microsoft/pages/responsepage.aspx?id=41OaSypLA0yoKGPBLTVM_zR74t7B3VJCujiML5HMn9RUOFBPUUcxSFFFVTdERjhSS0EwNlRJNkdZQy4u&route=shorturl' },
  { title: 'Voluntary Withdrawal Form', copy: 'Start a confidential conversation.', icon: 'edit-3' as const, tint: '#C88A62', url: 'https://forms.cloud.microsoft/pages/responsepage.aspx?id=41OaSypLA0yoKGPBLTVM_zR74t7B3VJCujiML5HMn9RUN1RLUzNFSUlZUFpRS0FYRDBXSVVFOUVBTy4u&route=shorturl' },
];
const resources = [
  { title: 'Policy Handbook', copy: 'Important guidelines for every family', icon: 'book-open' as const, url: 'https://legendaryprep-my.sharepoint.com/:b:/g/personal/staff_legendaryprepacademy_com/IQC5JjUfIdx-S45erfC44vBDATpaTpK5pZ1wJA_2U6CCz3k' },
  { title: 'Protect the culture', copy: 'Our shared commitment to one another', icon: 'heart' as const, url: 'https://legendaryprep-my.sharepoint.com/:b:/g/personal/staff_legendaryprepacademy_com/IQDWil7XQYXoSYQ49K1g4jeJAUNMbpJ3dxpwyyZpPfDN_eQ' },
  { title: 'EdOptions LMA: CIM', copy: 'Open the learning platform', icon: 'external-link' as const, url: 'https://cimlearn.com/login?next=%2Fclasses' },
];

export default function ParentHubScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { submissions, addSubmission } = useApp();
  const [activeForm, setActiveForm] = useState<string | null>(null);
  const [note, setNote] = useState('');
  const submit = () => { if (!activeForm) return; addSubmission(activeForm); setActiveForm(null); setNote(''); };
  return <View style={[styles.container, { backgroundColor: colors.background }]}>
    <ScrollView contentContainerStyle={{ paddingTop: insets.top + 18, paddingBottom: 115 }} showsVerticalScrollIndicator={false}>
      <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>FAMILY RESOURCES</Text><Text style={[styles.title, { color: colors.foreground }]}>Parent Hub</Text></View><View style={[styles.headerIcon, { backgroundColor: `${colors.accent}35` }]}><Feather name="bookmark" size={18} color={colors.accentForeground} /></View></View>
      <Text style={[styles.intro, { color: colors.mutedForeground }]}>Your one-stop resource for staying connected throughout the season.</Text>
      <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Forms</Text>
       <View style={styles.list}>{forms.map((form) => <Pressable key={form.title} onPress={() => void Linking.openURL(form.url)} style={({ pressed }) => [styles.resource, { backgroundColor: colors.card, borderColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><View style={[styles.resourceIcon, { backgroundColor: `${form.tint}18` }]}><Feather name={form.icon} size={19} color={form.tint} /></View><View style={{ flex: 1 }}><Text style={[styles.resourceTitle, { color: colors.foreground }]}>{form.title}</Text><Text style={[styles.resourceCopy, { color: colors.mutedForeground }]}>{form.copy}</Text></View><Feather name="arrow-up-right" size={16} color={colors.mutedForeground} /></Pressable>)}</View>
       <Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 24 }]}>Resources & Tools</Text>
      <View style={styles.list}>{resources.map((resource) => <Pressable key={resource.title} onPress={() => void Linking.openURL(resource.url)} style={({ pressed }) => [styles.resource, { backgroundColor: colors.card, borderColor: colors.border, opacity: pressed ? 0.7 : 1 }]}><View style={[styles.resourceIcon, { backgroundColor: `${colors.primary}14` }]}><Feather name={resource.icon} size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.resourceTitle, { color: colors.foreground }]}>{resource.title}</Text><Text style={[styles.resourceCopy, { color: colors.mutedForeground }]}>{resource.copy}</Text></View><Feather name="external-link" size={15} color={colors.mutedForeground} /></Pressable>)}</View>
      {submissions.length > 0 && <><Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 24 }]}>Your submissions</Text><View style={[styles.submissionCard, { backgroundColor: colors.card, borderColor: colors.border }]}>{submissions.slice(0, 3).map((item) => <View key={item.id} style={styles.submission}><View style={[styles.check, { backgroundColor: `${colors.primary}18` }]}><Feather name="check" size={13} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.resourceTitle, { color: colors.foreground }]}>{item.type}</Text><Text style={[styles.resourceCopy, { color: colors.mutedForeground }]}>{item.date}</Text></View><Text style={[styles.status, { color: colors.primary }]}>{item.status}</Text></View>)}</View></>}
    </ScrollView>
    <Modal visible={!!activeForm} transparent animationType="slide" onRequestClose={() => setActiveForm(null)}><View style={styles.modalBackdrop}><View style={[styles.modal, { backgroundColor: colors.card }]}><View style={styles.modalHandle} /><View style={styles.modalHeader}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>NEW SUBMISSION</Text><Text style={[styles.modalTitle, { color: colors.foreground }]}>{activeForm}</Text></View><Pressable onPress={() => setActiveForm(null)}><Feather name="x" size={21} color={colors.mutedForeground} /></Pressable></View><Text style={[styles.modalCopy, { color: colors.mutedForeground }]}>Add a note for the staff team. They’ll follow up if anything else is needed.</Text><TextInput multiline value={note} onChangeText={setNote} placeholder="Add details (optional)" placeholderTextColor={colors.mutedForeground} style={[styles.noteInput, { color: colors.foreground, borderColor: colors.border }]} /><Pressable testID="submit-form" onPress={submit} style={[styles.submit, { backgroundColor: colors.primary }]}><Text style={styles.submitText}>Submit form</Text><Feather name="arrow-up-right" size={16} color="#fff" /></Pressable></View></View></Modal>
  </View>;
}

const styles = StyleSheet.create({
  container: { flex: 1 }, header: { paddingHorizontal: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.3, marginBottom: 6 }, title: { fontFamily: 'Inter_700Bold', fontSize: 29, letterSpacing: -0.8 }, headerIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, intro: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginHorizontal: 22, marginBottom: 25, maxWidth: 310 }, sectionTitle: { fontFamily: 'Inter_700Bold', fontSize: 16, marginHorizontal: 22, marginBottom: 11 }, list: { gap: 9, marginHorizontal: 18 }, resource: { minHeight: 73, padding: 13, borderRadius: 17, borderWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 12 }, resourceIcon: { width: 39, height: 39, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, resourceTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13, marginBottom: 4 }, resourceCopy: { fontFamily: 'Inter_400Regular', fontSize: 11 }, submissionCard: { marginHorizontal: 18, borderWidth: 1, borderRadius: 17, overflow: 'hidden' }, submission: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 13, borderBottomWidth: 1, borderBottomColor: '#D9DED9' }, check: { width: 29, height: 29, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, status: { fontFamily: 'Inter_600SemiBold', fontSize: 10 }, modalBackdrop: { flex: 1, backgroundColor: '#12233F88', justifyContent: 'flex-end' }, modal: { borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 22, paddingBottom: 34 }, modalHandle: { width: 38, height: 4, borderRadius: 2, backgroundColor: '#D9DED9', alignSelf: 'center', marginBottom: 22 }, modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, modalTitle: { fontFamily: 'Inter_700Bold', fontSize: 23, letterSpacing: -0.5 }, modalCopy: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: 14 }, noteInput: { minHeight: 105, borderWidth: 1, borderRadius: 15, padding: 13, marginTop: 18, fontFamily: 'Inter_400Regular', fontSize: 13, textAlignVertical: 'top' }, submit: { marginTop: 14, borderRadius: 15, height: 48, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, submitText: { color: '#fff', fontFamily: 'Inter_700Bold', fontSize: 13 },
});